- id: mdformat
  name: mdformat
  description: "CommonMark and Hallmark compliant Markdown formatter"
  entry: mdformat
  language: python
  types: [markdown]
  minimum_pre_commit_version: '1.0.0'
  additional_dependencies:
  - mdformat@0.7.22
  - mdformat-hallmark
